### ISSUE TITLE
The "Apprentice" card does not do damage to the tower.

### ISSUE THREAD

**Issue by ramillies** [arcomage/arcomage-hd#20]
As said in the title: the text on the "Apprentice" card says that it does two damage to the enemy tower, but in fact it just does two damage (so if the opponent has a wall, it is reduced first).

This bug could be easily fixed by replacing the line 807 of the file `src/data/cards.ts` with `change(o, 'tower', -2)`.

**Comment by tomchen** [comment]
Exactly. Thx.

It's now `damage(o, 2)` meaning "2 damage (wall first then tower)", it should be replaced by `change(o, 'tower', -2)` which is "2 damage to the tower"

**Comment by tomchen** [comment]
Fixed. I'll deploy the fix along with the [multiplayer feature](https://github.com/arcomage/arcomage-hd/tree/multiplayer) in the next version, maybe today or tomorrow
