### ISSUE TITLE
Enemy -1 Quarry?

### ISSUE THREAD

**Issue by TRe3B4RK** [arcomage/arcomage-hd#39]
The game does not allow for you to knock the enemy Resource to a zero level?
Quarry, Magic, Dungeon.

Was this done on purpose?  I have not played a version, were this was the case. 
Am i doing something wrong?

**Comment by tomchen** [comment]
Yes it's on purpose. The original Arcomage game does not allow any generator to be reduced to zero.

Actually in the very early versions of ArcoMage HD it's allowed. Someone mentioned that to me, I was not quite sure so I asked in the Discord "Might and Magic" server to make sure it's not allowed in the original game before I changed it here.

It's also mentioned in the tutorial image:
https://raw.githubusercontent.com/arcomage/arcomage-hd/main/misc/readme_images/manual.jpg
("Minimum generator ...")

**Comment by tomchen** [comment]
If zero is allowed, the player with 0 generator will get unreasonably horrible disadvantage. It'll perhaps also be possible that the game never ends, or becomes slow and boring when both player have 0 generator.

**Comment by TRe3B4RK** [comment]
The versions i have played, which allowed this, were a homebrew for the Nintendo DS & the Stand-Alone Windows 98 version from 3DO.

I just did some reading... here is a review of the Stand-Alone version.
"Unlike in the Might and Magic version of Arcomage, the stand-alone version allows resource generators to be knocked down to zero, and the computer tends to take full advantage of this fact whenever possible, leading to a great deal of cursing at the screen."
:)

You have been corroborated, and i guess that IS an original rule!  So, i am glad to be playing the authentic M&M version!

I do like the Acromage HD AI, too.  It is a much more worthy opponent, than the two versions i have played.
This truly represents a duel of mages!

Thank you!

**Comment by tomchen** [comment]
I searched the review you've read https://www.old-games.com/download/5055/arcomage . Nice review. And yes I believe in ArcoMage HD I fixed all those problems mentioned in the review: 0 generator; AI damaging itself, AI discarding valuable cards.

Enjoy the game.

**Comment by TRe3B4RK** [comment]
Thanks for your time, all the information, and most importantly your work!
Well done.

**Comment by tomchen** [comment]
For future reference:
a7ac788d890965c3d36047515a9c5f89fce952bd
dbc5683087998505f5881c683470b4d21dbc3bad
