### ISSUE TITLE
I18N (Translation / Localization)

### ISSUE THREAD

**Issue by tomchen** [arcomage/arcomage-hd#9]
See also [README § Translation Credits](https://github.com/arcomage/arcomage-hd#translation-credits)

<hr>

<details><summary><strong>Click to show the detailed instruction on how to help me translate it [No longer needed since the 10 langs are all complete, at least for the cards] </strong></summary>

### Help me translate it

[Tavern names and location names](https://github.com/arcomage/arcomage-hd/tree/main/src/i18n/taverns) have already been translated by extracting from the original M&M game.

I've [OCR](https://github.com/arcomage/arcomage-hd/tree/main/tools/ocr) (optical character recognition)'d the card names & descriptions in the 5 incomplete languages.

If you speak one of Czech (`cs`), Polish (`pl`) and want to help, please:

#### Translate General Strings

In [src/i18n/main/](https://github.com/arcomage/arcomage-hd/tree/main/src/i18n/main) folder, go to "**\<LANGCODE\>.ts**" file, click <kbd>Raw</kbd> button, then <kbd>Ctrl</kbd> + <kbd>S</kbd> to save the file.

Look at src/i18n/main/[en.ts](https://github.com/arcomage/arcomage-hd/blob/main/src/i18n/main/en.ts) file for the strings in English.

Translate the untranslated lines in "[src/i18n/main/](https://github.com/arcomage/arcomage-hd/tree/main/src/i18n/main)**\<LANGCODE\>.ts**" file, by changing the string on the right. For example, change `'Your Name': 'Your Name',` to `'Your Name': 'Votre nom',`

#### Translate Card Names & Descriptions

In [src/i18n/cards/](https://github.com/arcomage/arcomage-hd/tree/main/src/i18n/cards) folder, go to "**\<LANGCODE\>.ts**" file, click <kbd>Raw</kbd> button, then <kbd>Ctrl</kbd> + <kbd>S</kbd> to save the file.

Look at src/i18n/cards/[en.ts](https://github.com/arcomage/arcomage-hd/blob/main/src/i18n/cards/en.ts) file for the strings in English.

Please also refer to:

* [main_en_fixed.png](https://github.com/arcomage/arcomage-hd/blob/main/tools/img-processing/original/main_en_fixed.png) which is an image that includes all cards with text in English
* The same image but of your language in [tools/ocr/original](https://github.com/arcomage/arcomage-hd/tree/main/tools/ocr/original) folder
* [tools/i18n-temp](https://github.com/arcomage/arcomage-hd/tree/main/tools/i18n-temp)/**cards.\<LANGCODE\>.ts** files are filled with the text I got with OCR (optical character recognition), which could have poor quality, please retranslate it if it's nonsense, or verify and modify it if it's readable

Check and/or translate "[src/i18n/cards/](https://github.com/arcomage/arcomage-hd/tree/main/src/i18n/cards)**<LANGCODE\>.ts**" file:

```
name: '<Translated card name>',
desc: '<Translated card desciption>',
```

#### Send it to me

Create a pull request if you know how to do it, or just give me the translated text on [GitHub](https://github.com/arcomage/arcomage-hd/issues/9), or on [Reddit](https://www.reddit.com/r/MightAndMagic/comments/mhfx30/arcomage_hd_i_made_a_webbased_opensource_clone_of/), or on [celestialheavens forum](https://www.celestialheavens.com/forum/10/17288), or via email.

</details>

* [x] English (`en`)
* [x] French (`fr`)
* [x] German (`de`)
* [x] Simplified Chinese (`zh-Hans`)
* [x] Traditional Chinese (`zh-Hant`)
* [x] Russian (`ru`)
* [x] Spanish (`es`) (some newly added `main` strings incomplete)
* [x] Italian (`it`) (some newly added `main` strings incomplete)
* [x] Czech (`cs`) (`cards` & some newly added `main` strings incomplete)
* [x] Polish (`pl`) (`cards` & some newly added `main` strings incomplete)
* [x] Brazilian Portuguese (`pt-BR`)
* [x] Some newly added multiplayer-related strings may be untranslated in previously complete language versions:  `cs`, `es`, `it`, `pl`

**Comment by tomchen** [comment]
Nearly complete for all 10 languages, although some newly added multiplayer-related strings may be untranslated in cs, es, it, pl

**Comment by mateuscv** [comment]
Hello @tomchen, I'd like to contribute by translating the game to Brazilian Portuguese (pt-br). Is there an interest on your part, or are you drawing the line at the 10 done languages?

**Comment by tomchen** [comment]
@mateuscv Thx. Sure you can. Go ahead. Ask me if you don't know which files need to be translated

**Comment by tomchen** [comment]
@mateuscv It'll be `pt-BR`, [uppercase for the region code](https://www.w3.org/International/articles/language-tags/).

Not sure if there were official `pt-BR` or `pt` releases for *Might and Magic VII* & *Might and Magic VIII*. If they exist, we can extract text from the card image (w/ OCR) and tavern names from LOD files. There'are scripts in [tools folder](https://github.com/arcomage/arcomage-hd/tree/main/tools) to use.

If not, then you'll have to translate [them](https://github.com/arcomage/arcomage-hd/tree/main/src/i18n/) by yourself, but perhaps with the help of Google Translate & DeepL. Even though you are native speaker, machine translation then manual correction can make it faster and easier.

**Comment by tomchen** [comment]
Arabic and RTL support added in v1.4.7:

45c98a9c7eafd1a33885d944e0552bba4cde3619
6c0fdb2bc3899d334b462acaf31acf83bc5c247f
etc
